#version 430 compatibility

uniform vec3 minPos;
uniform vec3 maxPos; 

layout (std430, binding = 4) buffer Pos
{
	vec4 Positions [ ];
};

layout (std430, binding = 6) buffer Col 
{
	vec4 Colors [ ];
};

layout (local_size_x = 128, local_size_y = 1, local_size_z = 1) in;


void main()
{
	const vec3 G = vec3 (0.0f, -9.8f, 0.0f);
	uint g_id = gl_GlobalInvocationID.x;

	vec3 pos = Positions[g_id].xyz;

	Positions[g_id].xyz = pos;
}

